# Generated by Django 3.1.7 on 2021-03-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('publisher_email', models.EmailField(blank=True, max_length=254)),
                ('first_release', models.DateField(auto_now_add=True)),
                ('update_release', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('print_type', models.CharField(choices=[('ex', 'excellent fine print'), ('sn', 'student version print'), ('eb', 'e-book version')], default='ex', max_length=2)),
                ('available_to_public', models.BooleanField(default=False)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
