# Generated by Django 3.1.7 on 2021-03-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandeshModel', '0002_remove_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name'], 'verbose_name_plural': 'books'},
        ),
    ]
