# Generated by Django 3.1.7 on 2021-03-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandeshORM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('driver', models.ManyToManyField(related_name='Cars', to='sandeshORM.Owner')),
            ],
        ),
    ]
