# Generated by Django 3.1.7 on 2021-03-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandeshORM', '0002_car2_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car2',
            name='driver',
            field=models.ManyToManyField(related_name='Cars', to='sandeshORM.Driver'),
        ),
    ]
