# Generated by Django 3.1.7 on 2021-03-18 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandeshORM', '0003_auto_20210318_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car1',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car', to='sandeshORM.owner1'),
        ),
    ]
